# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
before_install:
  - apt-get install build-essential
  - apt-get install install g++
  - apt-get install libusb-1.0-0-dev
  - cd nfcreader/src/
  - make
  - export LD_LIBRARY_PATH="$./libCR95HF.so:$LD_LIBRARY_PATH"
  - cd /
  - sudo cp /home/travis/build/IanEdwards99/nfcreader/nfcreader/src/libCR95HF.so .
  - cd /home/travis/build/IanEdwards99/nfcreader/
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: IanEdwards99
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: EDWIAN004@myuct.ac.za/nfcreader
    python: 3.5
git: #added line
  lfs_skip_smudge: true